name       : libxcomposite
version    : 0.4.4
release    : 8
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXcomposite-0.4.4.tar.gz : 83c04649819c6f52cda1b0ce8bcdcc48ad8618428ad803fb07f20b802f1bdad1
license    :
    - MIT
summary    : client library for the Composite extension to the X11 protocol
component  : xorg.library
description: |
    libXcomposite provides an X Window System client interface to the Composite
    extension to the X protocol. The Composite extension allows clients called
    compositing managers to control the final drawing of the screen.
    Rendering is done into an off-screen buffer.
builddeps  :
    - pkgconfig(compositeproto)
    - pkgconfig32(xfixes)
    - pkgconfig32(x11)
emul32     : yes
optimize   : speed
patterns   :
    - /usr/share/man
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
