name       : libxcomposite
version    : 0.4.5
release    : 13
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXcomposite-0.4.5.tar.gz : 581c7fc0f41a99af38b1c36b9be64bc13ef3f60091cd3f01105bbc7c01617d6c
license    : MIT
summary    : client library for the Composite extension to the X11 protocol
component  : xorg.library
description: |
    libXcomposite provides an X Window System client interface to the Composite extension to the X protocol. The Composite extension allows clients called compositing managers to control the final drawing of the screen. Rendering is done into an off-screen buffer.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig(xproto)
    - pkgconfig32(xfixes)
    - pkgconfig32(x11)
patterns   :
    - /usr/share/man
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
